export enum OrderStatus {
  REGISTRADA = 'REGISTRADA',
  ASIGNADA = 'ASIGNADA',
  LISTA_PARA_DESPACHO = 'LISTA_PARA_DESPACHO',
  EN_TRANSITO = 'EN_TRANSITO',
  ENTREGADA = 'ENTREGADA',
  BLOQUEADA = 'BLOQUEADA',
  CANCELADA = 'CANCELADA',
}
