export enum UserRole {
  CLIENTE = 'CLIENTE',
  AGENTE_OPERATIVO = 'AGENTE_OPERATIVO',
  AGENTE_LOGISTICO = 'AGENTE_LOGISTICO',
  ENCARGADO_PATIO = 'ENCARGADO_PATIO',
  PILOTO = 'PILOTO',
  AGENTE_FINANCIERO = 'AGENTE_FINANCIERO',
  GERENCIA = 'GERENCIA',
  ADMIN = 'ADMIN',
}
