import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { DataSource } from 'typeorm';
import { getDatabaseRuntimeConfig } from '../config/database-env';

interface SchemaState {
  tableCount: number;
  viewCount: number;
  hasPrimaryContactColumns: boolean;
  hasUserSessions: boolean;
  hasPaymentSupportField: boolean;
  hasClientBalanceView: boolean;
}

async function getSchemaState(dataSource: DataSource): Promise<SchemaState> {
  const counts = await dataSource.query<{
    table_count: string;
    view_count: string;
  }>(
    `SELECT
        COUNT(*) FILTER (WHERE table_type = 'BASE TABLE')::text AS table_count,
        COUNT(*) FILTER (WHERE table_type = 'VIEW')::text AS view_count
      FROM information_schema.tables
      WHERE table_schema = 'public'`,
  );

  const columns = await dataSource.query<{
    has_primary_contact_columns: boolean;
    has_user_sessions: boolean;
    has_payment_support_field: boolean;
    has_client_balance_view: boolean;
  }>(
    `SELECT
        EXISTS(
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'clients'
            AND column_name = 'primary_contact_name'
        ) AS has_primary_contact_columns,
        EXISTS(
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'user_sessions'
            AND column_name = 'session_token'
        ) AS has_user_sessions,
        EXISTS(
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'payments'
            AND column_name = 'support_document_path'
        ) AS has_payment_support_field,
        EXISTS(
          SELECT 1
          FROM information_schema.views
          WHERE table_schema = 'public'
            AND table_name = 'v_client_balances'
        ) AS has_client_balance_view`,
  );

  return {
    tableCount: parseInt(counts[0]?.table_count || '0', 10),
    viewCount: parseInt(counts[0]?.view_count || '0', 10),
    hasPrimaryContactColumns: Boolean(columns[0]?.has_primary_contact_columns),
    hasUserSessions: Boolean(columns[0]?.has_user_sessions),
    hasPaymentSupportField: Boolean(columns[0]?.has_payment_support_field),
    hasClientBalanceView: Boolean(columns[0]?.has_client_balance_view),
  };
}

function isCanonicalSchema(state: SchemaState): boolean {
  return (
    state.hasPrimaryContactColumns &&
    state.hasUserSessions &&
    state.hasPaymentSupportField &&
    state.hasClientBalanceView
  );
}

async function resetPublicSchema(dataSource: DataSource): Promise<void> {
  await dataSource.query('DROP SCHEMA IF EXISTS public CASCADE');
  await dataSource.query('CREATE SCHEMA public');
  await dataSource.query('GRANT ALL ON SCHEMA public TO public');
}

async function readCanonicalSql(): Promise<string> {
  const filePath = join(process.cwd(), '..', 'db', 'logitrans_postgresql.sql');
  return readFile(filePath, 'utf8');
}

function extractRoutine(sql: string, functionName: string): string {
  const pattern = new RegExp(
    `CREATE OR REPLACE FUNCTION ${functionName}\\([\\s\\S]*?\\$\\$;`,
    'i',
  );
  const match = sql.match(pattern);

  if (!match) {
    throw new Error(`No se pudo extraer la funcion ${functionName} del SQL canonico.`);
  }

  return match[0];
}

async function refreshCanonicalRoutines(dataSource: DataSource): Promise<void> {
  const sql = await readCanonicalSql();
  const routines = [
    'SYNC_CONTRACT_DEFAULTS',
    'VALIDATE_TRANSPORT_UNIT',
    'VALIDATE_ORDER_ASSIGNMENT',
    'VALIDATE_ORDER_COMMERCIAL_RULES',
    'POPULATE_INVOICE_FROM_ORDER',
    'AUTO_CREATE_DRAFT_INVOICE',
    'VALIDATE_PAYMENT_AMOUNT',
    'SYNC_INVOICE_PAYMENT',
  ];

  for (const name of routines) {
    try {
      const routineSql = extractRoutine(sql, name);
      await dataSource.query(routineSql);
    } catch (err) {
      console.warn(`No se pudo refrescar la rutina ${name}:`, (err as Error).message);
    }
  }
}

type IdentityColumnRow = {
  table_name: string;
  column_name: string;
};

type IdentitySequenceRow = {
  table_name: string;
  column_name: string;
  sequence_name: string | null;
};

async function relaxIdentityColumnsToByDefault(dataSource: DataSource): Promise<void> {
  const rawRows = await dataSource.query(
    `SELECT table_name, column_name
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND is_identity = 'YES'
        AND identity_generation = 'ALWAYS'
        AND column_name LIKE '%\_id' ESCAPE '\\'`,
  );

  if (!Array.isArray(rawRows)) {
    return;
  }

  const identityColumns = rawRows as IdentityColumnRow[];
  for (const row of identityColumns) {
    await dataSource.query(
      `ALTER TABLE public."${row.table_name}" ALTER COLUMN "${row.column_name}" SET GENERATED BY DEFAULT`,
    );
  }
}

export async function alignIdentitySequences(dataSource: DataSource): Promise<void> {
  const rawRows = await dataSource.query(
    `SELECT
        table_name,
        column_name,
        pg_get_serial_sequence(
          format('%I.%I', table_schema, table_name),
          column_name
        ) AS sequence_name
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND is_identity = 'YES'
        AND column_name LIKE '%\_id' ESCAPE '\\'`,
  );

  if (!Array.isArray(rawRows)) {
    return;
  }

  const identitySequences = rawRows as IdentitySequenceRow[];

  for (const row of identitySequences) {
    if (!row.sequence_name) {
      continue;
    }

    const maxIdRows = await dataSource.query<{ max_id: string | number | null }>(
      `SELECT COALESCE(MAX("${row.column_name}"), 0) AS max_id
        FROM public."${row.table_name}"`,
    );

    const maxIdRaw = maxIdRows[0]?.max_id;
    const maxId = Number(maxIdRaw ?? 0);

    if (maxId > 0) {
      await dataSource.query('SELECT setval($1::regclass, $2, true)', [
        row.sequence_name,
        maxId,
      ]);
      continue;
    }

    await dataSource.query('SELECT setval($1::regclass, 1, false)', [
      row.sequence_name,
    ]);
  }
}

export async function ensureCanonicalSchema(
  dataSource: DataSource,
): Promise<'created' | 'existing'> {
  const config = getDatabaseRuntimeConfig();
  let state = await getSchemaState(dataSource);

  if (config.resetOnBoot && (state.tableCount > 0 || state.viewCount > 0)) {
    await resetPublicSchema(dataSource);
    state = await getSchemaState(dataSource);
  }

  if (isCanonicalSchema(state)) {
    await relaxIdentityColumnsToByDefault(dataSource);
    await alignIdentitySequences(dataSource);
    await refreshCanonicalRoutines(dataSource);
    return 'existing';
  }

  if (state.tableCount > 0 || state.viewCount > 0) {
    throw new Error(
      'Se detecto un esquema PostgreSQL previo que no coincide con el modelo canonico. Elimine la base/volumen actual o arranque con DB_RESET_ON_BOOT=true para recrearla.',
    );
  }

  const sql = await readCanonicalSql();
  await dataSource.query(sql);
  await relaxIdentityColumnsToByDefault(dataSource);
  await alignIdentitySequences(dataSource);

  return 'created';
}