BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SEQUENCE IF NOT EXISTS SEQ_CLIENT_CODE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CONTRACT_NUMBER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ORDER_NUMBER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE_NUMBER START WITH 1 INCREMENT BY 1;

CREATE TYPE USER_ROLE AS ENUM (
    'CLIENTE',
    'AGENTE_OPERATIVO',
    'AGENTE_LOGISTICO',
    'ENCARGADO_PATIO',
    'PILOTO',
    'AGENTE_FINANCIERO',
    'GERENCIA',
    'ADMIN'
);

CREATE TYPE RISK_LEVEL AS ENUM ('BAJO', 'MEDIO', 'ALTO', 'CRITICO');

CREATE TYPE CONTRACT_STATUS AS ENUM (
    'BORRADOR',
    'PENDIENTE',
    'VIGENTE',
    'VENCIDO',
    'RECHAZADO',
    'CANCELADO'
);

CREATE TYPE ORDER_STATUS AS ENUM (
    'REGISTRADA',
    'ASIGNADA',
    'LISTA_PARA_DESPACHO',
    'EN_TRANSITO',
    'ENTREGADA',
    'BLOQUEADA',
    'CANCELADA'
);

CREATE TYPE ROUTE_EVENT_TYPE AS ENUM (
    'SALIDA',
    'PUNTO_CONTROL',
    'ADUANA',
    'INCIDENTE',
    'LLEGADA',
    'OTRO'
);

CREATE TYPE INVOICE_STATUS AS ENUM (
    'BORRADOR',
    'CERTIFICADA',
    'ENVIADA',
    'PAGADA',
    'RECHAZADA'
);

CREATE TYPE PAYMENT_METHOD AS ENUM ('TARJETA', 'TRANSFERENCIA');

CREATE TYPE PAYMENT_STATUS AS ENUM ('PENDIENTE', 'APROBADO', 'RECHAZADO');

CREATE TABLE CLIENTS (
    CLIENT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLIENT_CODE VARCHAR(30) NOT NULL UNIQUE DEFAULT ('CLI-' || LPAD(nextval('SEQ_CLIENT_CODE')::TEXT, 5, '0')),
    LEGAL_NAME VARCHAR(180) NOT NULL,
    COMMERCIAL_NAME VARCHAR(180),
    NIT VARCHAR(13) NOT NULL UNIQUE,
    TAX_ADDRESS TEXT NOT NULL,
    CONTACT_NAME VARCHAR(160) NOT NULL,
    CONTACT_EMAIL VARCHAR(320) NOT NULL,
    CONTACT_PHONE VARCHAR(30),
    CREDIT_LIMIT NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (CREDIT_LIMIT >= 0),
    PAYMENT_RISK RISK_LEVEL NOT NULL DEFAULT 'MEDIO',
    CUSTOMS_RISK RISK_LEVEL NOT NULL DEFAULT 'MEDIO',
    CARGO_RISK RISK_LEVEL NOT NULL DEFAULT 'MEDIO',
    AML_RISK RISK_LEVEL NOT NULL DEFAULT 'MEDIO',
    IS_BLOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    BLOCK_REASON TEXT,
    CHECK (char_length(NIT) = 13)
);

CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLIENT_ID UUID REFERENCES CLIENTS (CLIENT_ID),
    ROLE USER_ROLE NOT NULL,
    FULL_NAME VARCHAR(160) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    PHONE VARCHAR(30),
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (
        (ROLE = 'CLIENTE' AND CLIENT_ID IS NOT NULL)
        OR (ROLE <> 'CLIENTE' AND CLIENT_ID IS NULL)
    )
);

CREATE TABLE PASSWORD_RECOVERY_TOKENS (
    TOKEN_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NOT NULL REFERENCES USERS (USER_ID),
    TOKEN_HASH TEXT NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    USED_AT TIMESTAMPTZ
);

CREATE TABLE CLIENT_CARDS (
    CARD_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLIENT_ID UUID NOT NULL REFERENCES CLIENTS (CLIENT_ID),
    CARD_ALIAS VARCHAR(80) NOT NULL,
    CARD_BRAND VARCHAR(30) NOT NULL,
    LAST_FOUR CHAR(4) NOT NULL,
    EXPIRATION_MONTH SMALLINT NOT NULL CHECK (EXPIRATION_MONTH BETWEEN 1 AND 12),
    EXPIRATION_YEAR SMALLINT NOT NULL CHECK (EXPIRATION_YEAR BETWEEN 2025 AND 2100),
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (CLIENT_ID, CARD_ALIAS)
);

CREATE TABLE BRANCHES (
    BRANCH_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BRANCH_CODE VARCHAR(20) NOT NULL UNIQUE,
    BRANCH_NAME VARCHAR(100) NOT NULL UNIQUE,
    CITY VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ROUTES (
    ROUTE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROUTE_CODE VARCHAR(30) NOT NULL UNIQUE,
    ORIGIN VARCHAR(120) NOT NULL,
    DESTINATION VARCHAR(120) NOT NULL,
    DISTANCE_KM NUMERIC(10, 2) NOT NULL CHECK (DISTANCE_KM > 0),
    ESTIMATED_HOURS NUMERIC(10, 2) NOT NULL CHECK (ESTIMATED_HOURS > 0),
    IS_INTERNATIONAL BOOLEAN NOT NULL DEFAULT FALSE,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (ORIGIN, DESTINATION)
);

CREATE TABLE VEHICLE_TYPES (
    VEHICLE_TYPE_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TYPE_CODE VARCHAR(20) NOT NULL UNIQUE,
    TYPE_NAME VARCHAR(100) NOT NULL UNIQUE,
    MIN_CAPACITY_TON NUMERIC(6, 2) NOT NULL CHECK (MIN_CAPACITY_TON >= 0),
    MAX_CAPACITY_TON NUMERIC(6, 2),
    RATE_PER_KM NUMERIC(12, 2) NOT NULL CHECK (RATE_PER_KM > 0),
    CHECK (MAX_CAPACITY_TON IS NULL OR MAX_CAPACITY_TON >= MIN_CAPACITY_TON)
);

CREATE TABLE CARGO_TYPES (
    CARGO_TYPE_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARGO_NAME VARCHAR(100) NOT NULL UNIQUE,
    REQUIRES_REFRIGERATION BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE CONTRACTS (
    CONTRACT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CONTRACT_NUMBER VARCHAR(40) NOT NULL UNIQUE DEFAULT ('CONT-' || LPAD(nextval('SEQ_CONTRACT_NUMBER')::TEXT, 5, '0')),
    CLIENT_ID UUID NOT NULL REFERENCES CLIENTS (CLIENT_ID),
    STATUS CONTRACT_STATUS NOT NULL DEFAULT 'BORRADOR',
    START_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    END_DATE DATE NOT NULL DEFAULT ((CURRENT_DATE + INTERVAL '1 year')::DATE),
    ACCEPTED_AT TIMESTAMPTZ,
    CREDIT_LIMIT NUMERIC(14, 2) NOT NULL CHECK (CREDIT_LIMIT >= 0),
    PAYMENT_TERM_DAYS SMALLINT NOT NULL CHECK (PAYMENT_TERM_DAYS IN (15, 30, 45)),
    DISCOUNT_PERCENTAGE NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (
        DISCOUNT_PERCENTAGE >= 0 AND DISCOUNT_PERCENTAGE <= 100
    ),
    SIGNED_CONTRACT_PATH TEXT,
    NOTES TEXT,
    CHECK (END_DATE >= START_DATE)
);

CREATE TABLE CONTRACT_ROUTES (
    CONTRACT_ROUTE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CONTRACT_ID UUID NOT NULL REFERENCES CONTRACTS (CONTRACT_ID),
    ROUTE_ID BIGINT NOT NULL REFERENCES ROUTES (ROUTE_ID),
    PROMISED_DELIVERY_HOURS NUMERIC(10, 2) NOT NULL CHECK (PROMISED_DELIVERY_HOURS > 0),
    UNIQUE (CONTRACT_ID, ROUTE_ID),
    UNIQUE (CONTRACT_ROUTE_ID, CONTRACT_ID)
);

CREATE TABLE CONTRACT_CARGO_TYPES (
    CONTRACT_ID UUID NOT NULL REFERENCES CONTRACTS (CONTRACT_ID),
    CARGO_TYPE_ID SMALLINT NOT NULL REFERENCES CARGO_TYPES (CARGO_TYPE_ID),
    PRIMARY KEY (CONTRACT_ID, CARGO_TYPE_ID)
);

CREATE TABLE CONTRACT_RATES (
    CONTRACT_RATE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CONTRACT_ID UUID NOT NULL REFERENCES CONTRACTS (CONTRACT_ID),
    VEHICLE_TYPE_ID SMALLINT NOT NULL REFERENCES VEHICLE_TYPES (VEHICLE_TYPE_ID),
    BASE_RATE_PER_KM NUMERIC(12, 2) NOT NULL CHECK (BASE_RATE_PER_KM > 0),
    DISCOUNT_PERCENTAGE NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (
        DISCOUNT_PERCENTAGE >= 0 AND DISCOUNT_PERCENTAGE <= 100
    ),
    FINAL_RATE_PER_KM NUMERIC(12, 2) NOT NULL CHECK (FINAL_RATE_PER_KM > 0),
    UNIQUE (CONTRACT_ID, VEHICLE_TYPE_ID),
    UNIQUE (CONTRACT_RATE_ID, CONTRACT_ID),
    CHECK (FINAL_RATE_PER_KM <= BASE_RATE_PER_KM)
);

CREATE TABLE TRANSPORT_UNITS (
    UNIT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    BRANCH_ID SMALLINT NOT NULL REFERENCES BRANCHES (BRANCH_ID),
    VEHICLE_TYPE_ID SMALLINT NOT NULL REFERENCES VEHICLE_TYPES (VEHICLE_TYPE_ID),
    PILOT_USER_ID UUID UNIQUE REFERENCES USERS (USER_ID),
    PLATE_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    VEHICLE_MODEL VARCHAR(80),
    CAPACITY_TON NUMERIC(6, 2) NOT NULL CHECK (CAPACITY_TON > 0),
    HAS_REFRIGERATION BOOLEAN NOT NULL DEFAULT FALSE,
    PILOT_LICENSE_NUMBER VARCHAR(40) NOT NULL UNIQUE,
    PILOT_LICENSE_EXPIRATION DATE NOT NULL,
    VEHICLE_DOCUMENT_EXPIRATION DATE NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ORDERS (
    ORDER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ORDER_NUMBER VARCHAR(40) NOT NULL UNIQUE DEFAULT ('ORD-' || LPAD(nextval('SEQ_ORDER_NUMBER')::TEXT, 6, '0')),
    CONTRACT_ID UUID NOT NULL REFERENCES CONTRACTS (CONTRACT_ID),
    REQUESTED_BY_USER_ID UUID NOT NULL REFERENCES USERS (USER_ID),
    BRANCH_ID SMALLINT REFERENCES BRANCHES (BRANCH_ID),
    CONTRACT_ROUTE_ID UUID,
    CONTRACT_RATE_ID UUID,
    CARGO_TYPE_ID SMALLINT NOT NULL REFERENCES CARGO_TYPES (CARGO_TYPE_ID),
    UNIT_ID UUID REFERENCES TRANSPORT_UNITS (UNIT_ID),
    STATUS ORDER_STATUS NOT NULL DEFAULT 'REGISTRADA',
    CARGO_DESCRIPTION TEXT NOT NULL DEFAULT 'PENDIENTE_DETALLE',
    DECLARED_WEIGHT_TON NUMERIC(8, 2) NOT NULL CHECK (DECLARED_WEIGHT_TON > 0),
    LOADED_WEIGHT_TON NUMERIC(8, 2) CHECK (LOADED_WEIGHT_TON > 0),
    PICKUP_ADDRESS TEXT NOT NULL,
    DELIVERY_ADDRESS TEXT NOT NULL,
    REQUESTED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    SCHEDULED_PICKUP_AT TIMESTAMPTZ,
    PROMISED_DELIVERY_AT TIMESTAMPTZ,
    DISPATCHED_AT TIMESTAMPTZ,
    DELIVERED_AT TIMESTAMPTZ,
    STOWAGE_CONFIRMED BOOLEAN,
    IS_SEALED BOOLEAN,
    RECEIVER_NAME VARCHAR(160),
    RECEIVER_SIGNATURE_PATH TEXT,
    DELIVERY_EVIDENCE_PATH TEXT,
    DISTANCE_KM NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (DISTANCE_KM >= 0),
    BASE_RATE_PER_KM NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (BASE_RATE_PER_KM >= 0),
    DISCOUNT_PERCENTAGE NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (
        DISCOUNT_PERCENTAGE >= 0 AND DISCOUNT_PERCENTAGE <= 100
    ),
    FINAL_RATE_PER_KM NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (FINAL_RATE_PER_KM >= 0),
    SUBTOTAL_AMOUNT NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (SUBTOTAL_AMOUNT >= 0),
    TAX_AMOUNT NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (TAX_AMOUNT >= 0),
    TOTAL_AMOUNT NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (TOTAL_AMOUNT >= 0),
    FUEL_COST NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (FUEL_COST >= 0),
    VIATICS_COST NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (VIATICS_COST >= 0),
    MAINTENANCE_COST NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (MAINTENANCE_COST >= 0),
    NOTES TEXT,
    CONSTRAINT FK_ORDERS_CONTRACT_ROUTE FOREIGN KEY (CONTRACT_ROUTE_ID, CONTRACT_ID)
        REFERENCES CONTRACT_ROUTES (CONTRACT_ROUTE_ID, CONTRACT_ID),
    CONSTRAINT FK_ORDERS_CONTRACT_RATE FOREIGN KEY (CONTRACT_RATE_ID, CONTRACT_ID)
        REFERENCES CONTRACT_RATES (CONTRACT_RATE_ID, CONTRACT_ID),
    CHECK (TOTAL_AMOUNT = SUBTOTAL_AMOUNT + TAX_AMOUNT),
    CHECK (
        SCHEDULED_PICKUP_AT IS NULL OR PROMISED_DELIVERY_AT IS NULL
        OR PROMISED_DELIVERY_AT >= SCHEDULED_PICKUP_AT
    )
);

CREATE TABLE ORDER_ROUTE_LOGS (
    LOG_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ORDER_ID UUID NOT NULL REFERENCES ORDERS (ORDER_ID),
    EVENT_TYPE ROUTE_EVENT_TYPE NOT NULL,
    EVENT_TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE INVOICES (
    INVOICE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    INVOICE_NUMBER VARCHAR(40) NOT NULL UNIQUE DEFAULT ('FAC-' || LPAD(nextval('SEQ_INVOICE_NUMBER')::TEXT, 6, '0')),
    ORDER_ID UUID NOT NULL UNIQUE REFERENCES ORDERS (ORDER_ID),
    CLIENT_ID UUID NOT NULL REFERENCES CLIENTS (CLIENT_ID),
    STATUS INVOICE_STATUS NOT NULL DEFAULT 'BORRADOR',
    ISSUE_DATE TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DUE_DATE DATE NOT NULL DEFAULT ((CURRENT_DATE + INTERVAL '30 day')::DATE),
    SENT_AT TIMESTAMPTZ,
    CLIENT_NAME VARCHAR(180) NOT NULL,
    CLIENT_NIT VARCHAR(13) NOT NULL,
    CLIENT_ADDRESS TEXT NOT NULL,
    SERVICE_DESCRIPTION TEXT NOT NULL,
    SUBTOTAL_AMOUNT NUMERIC(14, 2) NOT NULL CHECK (SUBTOTAL_AMOUNT >= 0),
    TAX_AMOUNT NUMERIC(14, 2) NOT NULL CHECK (TAX_AMOUNT >= 0),
    TOTAL_AMOUNT NUMERIC(14, 2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    FEL_UUID VARCHAR(50) UNIQUE,
    PDF_PATH TEXT,
    CHECK (char_length(CLIENT_NIT) = 13),
    CHECK (DUE_DATE >= ISSUE_DATE::DATE),
    CHECK (TOTAL_AMOUNT = SUBTOTAL_AMOUNT + TAX_AMOUNT)
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    INVOICE_ID UUID NOT NULL UNIQUE REFERENCES INVOICES (INVOICE_ID),
    METHOD PAYMENT_METHOD NOT NULL,
    STATUS PAYMENT_STATUS NOT NULL DEFAULT 'PENDIENTE',
    CARD_ID UUID REFERENCES CLIENT_CARDS (CARD_ID),
    BANK_REFERENCE VARCHAR(80),
    TRANSFER_RECEIPT_PATH TEXT,
    AMOUNT NUMERIC(14, 2) NOT NULL CHECK (AMOUNT > 0),
    PAYMENT_DATE TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    REVIEWED_BY_USER_ID UUID REFERENCES USERS (USER_ID),
    CHECK (
        (METHOD = 'TARJETA' AND CARD_ID IS NOT NULL AND TRANSFER_RECEIPT_PATH IS NULL AND BANK_REFERENCE IS NULL)
        OR (METHOD = 'TRANSFERENCIA' AND CARD_ID IS NULL AND TRANSFER_RECEIPT_PATH IS NOT NULL AND BANK_REFERENCE IS NOT NULL)
    )
);

CREATE INDEX IX_USERS_CLIENT_ROLE ON USERS (CLIENT_ID, ROLE);
CREATE INDEX IX_CONTRACTS_CLIENT_STATUS ON CONTRACTS (CLIENT_ID, STATUS);
CREATE INDEX IX_ORDERS_STATUS_BRANCH ON ORDERS (STATUS, BRANCH_ID);
CREATE INDEX IX_ORDERS_CONTRACT ON ORDERS (CONTRACT_ID);
CREATE INDEX IX_INVOICES_STATUS_DUE_DATE ON INVOICES (STATUS, DUE_DATE);
CREATE INDEX IX_LOGS_ORDER_TIME ON ORDER_ROUTE_LOGS (ORDER_ID, EVENT_TIME DESC);

CREATE UNIQUE INDEX UX_CLIENT_ACTIVE_CONTRACT
    ON CONTRACTS (CLIENT_ID)
    WHERE STATUS IN ('PENDIENTE', 'VIGENTE');

CREATE OR REPLACE FUNCTION SYNC_CONTRACT_DEFAULTS()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO CONTRACT_RATES (
        CONTRACT_ID,
        VEHICLE_TYPE_ID,
        BASE_RATE_PER_KM,
        DISCOUNT_PERCENTAGE,
        FINAL_RATE_PER_KM
    )
    SELECT
        NEW.CONTRACT_ID,
        VT.VEHICLE_TYPE_ID,
        VT.RATE_PER_KM,
        NEW.DISCOUNT_PERCENTAGE,
        ROUND(VT.RATE_PER_KM * (1 - NEW.DISCOUNT_PERCENTAGE / 100.0), 2)
    FROM VEHICLE_TYPES VT
    ON CONFLICT (CONTRACT_ID, VEHICLE_TYPE_ID)
    DO UPDATE SET
        BASE_RATE_PER_KM = EXCLUDED.BASE_RATE_PER_KM,
        DISCOUNT_PERCENTAGE = EXCLUDED.DISCOUNT_PERCENTAGE,
        FINAL_RATE_PER_KM = EXCLUDED.FINAL_RATE_PER_KM;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION VALIDATE_TRANSPORT_UNIT()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    V_MIN NUMERIC(6, 2);
    V_MAX NUMERIC(6, 2);
BEGIN
    SELECT MIN_CAPACITY_TON, MAX_CAPACITY_TON
      INTO V_MIN, V_MAX
    FROM VEHICLE_TYPES
    WHERE VEHICLE_TYPE_ID = NEW.VEHICLE_TYPE_ID;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'VEHICLE_TYPE_ID % no existe.', NEW.VEHICLE_TYPE_ID;
    END IF;

    IF NEW.CAPACITY_TON < V_MIN OR (V_MAX IS NOT NULL AND NEW.CAPACITY_TON > V_MAX) THEN
        RAISE EXCEPTION 'La capacidad % no coincide con el rango configurado del tipo de vehiculo.', NEW.CAPACITY_TON;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION VALIDATE_ORDER_ASSIGNMENT()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    V_CAPACITY NUMERIC(6, 2);
    V_HAS_REFRIGERATION BOOLEAN;
    V_REQUIRES_REFRIGERATION BOOLEAN;
        V_BRANCH_ID SMALLINT;
        V_VEHICLE_TYPE_ID SMALLINT;
        V_RATE_ID UUID;
        V_BASE_RATE NUMERIC(12, 2);
        V_FINAL_RATE NUMERIC(12, 2);
        V_DISTANCE NUMERIC(10, 2);
BEGIN
    IF NEW.UNIT_ID IS NULL THEN
                IF NEW.CONTRACT_ROUTE_ID IS NOT NULL AND NEW.DISTANCE_KM = 0 THEN
                        SELECT R.DISTANCE_KM
                            INTO V_DISTANCE
                        FROM CONTRACT_ROUTES CR
                        JOIN ROUTES R
                            ON R.ROUTE_ID = CR.ROUTE_ID
                        WHERE CR.CONTRACT_ROUTE_ID = NEW.CONTRACT_ROUTE_ID;

                        IF FOUND THEN
                                NEW.DISTANCE_KM = V_DISTANCE;
                        END IF;
                END IF;

                IF NEW.SUBTOTAL_AMOUNT = 0 AND NEW.DISTANCE_KM > 0 AND NEW.FINAL_RATE_PER_KM > 0 THEN
                        NEW.SUBTOTAL_AMOUNT = ROUND(NEW.DISTANCE_KM * NEW.FINAL_RATE_PER_KM, 2);
                        NEW.TAX_AMOUNT = ROUND(NEW.SUBTOTAL_AMOUNT * 0.12, 2);
                        NEW.TOTAL_AMOUNT = NEW.SUBTOTAL_AMOUNT + NEW.TAX_AMOUNT;
                END IF;

                RETURN NEW;
    END IF;

        SELECT CAPACITY_TON, HAS_REFRIGERATION, BRANCH_ID, VEHICLE_TYPE_ID
            INTO V_CAPACITY, V_HAS_REFRIGERATION, V_BRANCH_ID, V_VEHICLE_TYPE_ID
    FROM TRANSPORT_UNITS
    WHERE UNIT_ID = NEW.UNIT_ID;

    SELECT REQUIRES_REFRIGERATION
      INTO V_REQUIRES_REFRIGERATION
    FROM CARGO_TYPES
    WHERE CARGO_TYPE_ID = NEW.CARGO_TYPE_ID;

    IF NEW.DECLARED_WEIGHT_TON > V_CAPACITY THEN
        RAISE EXCEPTION 'El peso declarado % supera la capacidad de la unidad %.', NEW.DECLARED_WEIGHT_TON, V_CAPACITY;
    END IF;

    IF NEW.LOADED_WEIGHT_TON IS NOT NULL AND NEW.LOADED_WEIGHT_TON > V_CAPACITY THEN
        RAISE EXCEPTION 'El peso cargado % supera la capacidad de la unidad %.', NEW.LOADED_WEIGHT_TON, V_CAPACITY;
    END IF;

    IF V_REQUIRES_REFRIGERATION AND NOT V_HAS_REFRIGERATION THEN
        RAISE EXCEPTION 'La unidad asignada no cumple con el requisito de refrigeracion.';
    END IF;

    IF NEW.BRANCH_ID IS NULL THEN
        NEW.BRANCH_ID = V_BRANCH_ID;
    END IF;

    IF NEW.CONTRACT_RATE_ID IS NULL THEN
        SELECT CONTRACT_RATE_ID, BASE_RATE_PER_KM, FINAL_RATE_PER_KM
          INTO V_RATE_ID, V_BASE_RATE, V_FINAL_RATE
        FROM CONTRACT_RATES
        WHERE CONTRACT_ID = NEW.CONTRACT_ID
          AND VEHICLE_TYPE_ID = V_VEHICLE_TYPE_ID
        LIMIT 1;

        IF FOUND THEN
            NEW.CONTRACT_RATE_ID = V_RATE_ID;
            IF NEW.BASE_RATE_PER_KM = 0 THEN
                NEW.BASE_RATE_PER_KM = V_BASE_RATE;
            END IF;
            IF NEW.FINAL_RATE_PER_KM = 0 THEN
                NEW.FINAL_RATE_PER_KM = V_FINAL_RATE;
            END IF;
        END IF;
    END IF;

    IF NEW.CONTRACT_ROUTE_ID IS NOT NULL AND NEW.DISTANCE_KM = 0 THEN
        SELECT R.DISTANCE_KM
          INTO V_DISTANCE
        FROM CONTRACT_ROUTES CR
        JOIN ROUTES R
          ON R.ROUTE_ID = CR.ROUTE_ID
        WHERE CR.CONTRACT_ROUTE_ID = NEW.CONTRACT_ROUTE_ID;

        IF FOUND THEN
            NEW.DISTANCE_KM = V_DISTANCE;
        END IF;
    END IF;

    IF NEW.SUBTOTAL_AMOUNT = 0 AND NEW.DISTANCE_KM > 0 AND NEW.FINAL_RATE_PER_KM > 0 THEN
        NEW.SUBTOTAL_AMOUNT = ROUND(NEW.DISTANCE_KM * NEW.FINAL_RATE_PER_KM, 2);
        NEW.TAX_AMOUNT = ROUND(NEW.SUBTOTAL_AMOUNT * 0.12, 2);
        NEW.TOTAL_AMOUNT = NEW.SUBTOTAL_AMOUNT + NEW.TAX_AMOUNT;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION POPULATE_INVOICE_FROM_ORDER()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    V_CLIENT_ID UUID;
    V_CLIENT_NAME VARCHAR(180);
    V_CLIENT_NIT VARCHAR(13);
    V_CLIENT_ADDRESS TEXT;
    V_ORDER_NUMBER VARCHAR(40);
    V_TOTAL NUMERIC(14, 2);
    V_SUBTOTAL NUMERIC(14, 2);
    V_TAX NUMERIC(14, 2);
    V_TERM SMALLINT;
BEGIN
    SELECT
        C.CLIENT_ID,
        C.LEGAL_NAME,
        C.NIT,
        C.TAX_ADDRESS,
        O.ORDER_NUMBER,
        O.TOTAL_AMOUNT,
        O.SUBTOTAL_AMOUNT,
        O.TAX_AMOUNT,
        CT.PAYMENT_TERM_DAYS
      INTO
        V_CLIENT_ID,
        V_CLIENT_NAME,
        V_CLIENT_NIT,
        V_CLIENT_ADDRESS,
        V_ORDER_NUMBER,
        V_TOTAL,
        V_SUBTOTAL,
        V_TAX,
        V_TERM
    FROM ORDERS O
    JOIN CONTRACTS CT
      ON CT.CONTRACT_ID = O.CONTRACT_ID
    JOIN CLIENTS C
      ON C.CLIENT_ID = CT.CLIENT_ID
    WHERE O.ORDER_ID = NEW.ORDER_ID;

    IF NEW.CLIENT_ID IS NULL THEN
        NEW.CLIENT_ID = V_CLIENT_ID;
    END IF;

    IF NEW.CLIENT_NAME IS NULL OR NEW.CLIENT_NAME = '' THEN
        NEW.CLIENT_NAME = V_CLIENT_NAME;
    END IF;

    IF NEW.CLIENT_NIT IS NULL OR NEW.CLIENT_NIT = '' THEN
        NEW.CLIENT_NIT = V_CLIENT_NIT;
    END IF;

    IF NEW.CLIENT_ADDRESS IS NULL OR NEW.CLIENT_ADDRESS = '' THEN
        NEW.CLIENT_ADDRESS = V_CLIENT_ADDRESS;
    END IF;

    IF NEW.SERVICE_DESCRIPTION IS NULL OR NEW.SERVICE_DESCRIPTION = '' THEN
        NEW.SERVICE_DESCRIPTION = 'SERVICIO LOGISTICO DE LA ORDEN ' || V_ORDER_NUMBER;
    END IF;

    IF NEW.SUBTOTAL_AMOUNT = 0 THEN
        NEW.SUBTOTAL_AMOUNT = V_SUBTOTAL;
    END IF;

    IF NEW.TAX_AMOUNT = 0 THEN
        NEW.TAX_AMOUNT = V_TAX;
    END IF;

    IF NEW.TOTAL_AMOUNT = 0 THEN
        NEW.TOTAL_AMOUNT = V_TOTAL;
    END IF;

    IF NEW.DUE_DATE IS NULL THEN
        NEW.DUE_DATE = (COALESCE(NEW.ISSUE_DATE, NOW())::DATE + COALESCE(V_TERM, 30));
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION VALIDATE_PAYMENT_AMOUNT()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    V_TOTAL NUMERIC(14, 2);
BEGIN
    SELECT TOTAL_AMOUNT
      INTO V_TOTAL
    FROM INVOICES
    WHERE INVOICE_ID = NEW.INVOICE_ID;

    IF V_TOTAL IS NULL THEN
        RAISE EXCEPTION 'La factura % no existe.', NEW.INVOICE_ID;
    END IF;

    IF NEW.AMOUNT <> V_TOTAL THEN
        RAISE EXCEPTION 'El pago % debe coincidir exactamente con el total de la factura %.', NEW.AMOUNT, V_TOTAL;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION SYNC_INVOICE_PAYMENT()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.STATUS = 'APROBADO' THEN
        UPDATE INVOICES
        SET STATUS = 'PAGADA'
        WHERE INVOICE_ID = NEW.INVOICE_ID;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER TRG_VALIDATE_TRANSPORT_UNIT
BEFORE INSERT OR UPDATE ON TRANSPORT_UNITS
FOR EACH ROW
EXECUTE FUNCTION VALIDATE_TRANSPORT_UNIT();

CREATE TRIGGER TRG_SYNC_CONTRACT_DEFAULTS
AFTER INSERT OR UPDATE OF DISCOUNT_PERCENTAGE ON CONTRACTS
FOR EACH ROW
EXECUTE FUNCTION SYNC_CONTRACT_DEFAULTS();

CREATE TRIGGER TRG_VALIDATE_ORDER_ASSIGNMENT
BEFORE INSERT OR UPDATE ON ORDERS
FOR EACH ROW
EXECUTE FUNCTION VALIDATE_ORDER_ASSIGNMENT();

CREATE TRIGGER TRG_POPULATE_INVOICE_FROM_ORDER
BEFORE INSERT ON INVOICES
FOR EACH ROW
EXECUTE FUNCTION POPULATE_INVOICE_FROM_ORDER();

CREATE TRIGGER TRG_VALIDATE_PAYMENT_AMOUNT
BEFORE INSERT OR UPDATE ON PAYMENTS
FOR EACH ROW
EXECUTE FUNCTION VALIDATE_PAYMENT_AMOUNT();

CREATE TRIGGER TRG_SYNC_INVOICE_PAYMENT
AFTER INSERT OR UPDATE ON PAYMENTS
FOR EACH ROW
EXECUTE FUNCTION SYNC_INVOICE_PAYMENT();

CREATE OR REPLACE VIEW V_CLIENT_BALANCES AS
WITH INVOICE_TOTALS AS (
    SELECT
        C.CLIENT_ID,
        COALESCE(SUM(I.TOTAL_AMOUNT) FILTER (WHERE I.STATUS <> 'RECHAZADA'), 0) AS INVOICED_TOTAL,
        COUNT(*) FILTER (
            WHERE I.STATUS <> 'PAGADA'
              AND I.STATUS <> 'RECHAZADA'
              AND I.DUE_DATE < CURRENT_DATE
        ) AS OVERDUE_INVOICES
    FROM CLIENTS C
    LEFT JOIN CONTRACTS CT
        ON CT.CLIENT_ID = C.CLIENT_ID
    LEFT JOIN ORDERS O
        ON O.CONTRACT_ID = CT.CONTRACT_ID
    LEFT JOIN INVOICES I
        ON I.ORDER_ID = O.ORDER_ID
    GROUP BY C.CLIENT_ID
),
PAYMENTS_TOTALS AS (
    SELECT
        C.CLIENT_ID,
        COALESCE(SUM(P.AMOUNT) FILTER (WHERE P.STATUS = 'APROBADO'), 0) AS PAID_TOTAL
    FROM CLIENTS C
    LEFT JOIN CONTRACTS CT
        ON CT.CLIENT_ID = C.CLIENT_ID
    LEFT JOIN ORDERS O
        ON O.CONTRACT_ID = CT.CONTRACT_ID
    LEFT JOIN INVOICES I
        ON I.ORDER_ID = O.ORDER_ID
    LEFT JOIN PAYMENTS P
        ON P.INVOICE_ID = I.INVOICE_ID
    GROUP BY C.CLIENT_ID
)
SELECT
    C.CLIENT_ID,
    C.CLIENT_CODE,
    C.LEGAL_NAME,
    C.CREDIT_LIMIT,
    COALESCE(IT.INVOICED_TOTAL, 0) - COALESCE(PT.PAID_TOTAL, 0) AS OUTSTANDING_BALANCE,
    C.CREDIT_LIMIT - (COALESCE(IT.INVOICED_TOTAL, 0) - COALESCE(PT.PAID_TOTAL, 0)) AS AVAILABLE_CREDIT,
    COALESCE(IT.OVERDUE_INVOICES, 0) AS OVERDUE_INVOICES,
    (
        C.IS_BLOCKED
        OR COALESCE(IT.OVERDUE_INVOICES, 0) > 0
        OR C.CREDIT_LIMIT - (COALESCE(IT.INVOICED_TOTAL, 0) - COALESCE(PT.PAID_TOTAL, 0)) < 0
    ) AS SHOULD_BLOCK_ORDERS
FROM CLIENTS C
LEFT JOIN INVOICE_TOTALS IT
    ON IT.CLIENT_ID = C.CLIENT_ID
LEFT JOIN PAYMENTS_TOTALS PT
    ON PT.CLIENT_ID = C.CLIENT_ID;

CREATE OR REPLACE VIEW V_DAILY_OPERATIONS AS
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    DATE(O.REQUESTED_AT) AS OPERATION_DATE,
    COUNT(*) AS TOTAL_ORDERS,
    COUNT(*) FILTER (WHERE O.STATUS = 'ENTREGADA') AS DELIVERED_ORDERS,
    COALESCE(SUM(I.TOTAL_AMOUNT) FILTER (WHERE I.STATUS <> 'RECHAZADA'), 0) AS INVOICED_TOTAL,
    COUNT(*) FILTER (WHERE I.STATUS = 'PAGADA') AS PAID_INVOICES
FROM BRANCHES B
LEFT JOIN ORDERS O
    ON O.BRANCH_ID = B.BRANCH_ID
LEFT JOIN INVOICES I
    ON I.ORDER_ID = O.ORDER_ID
GROUP BY B.BRANCH_ID, B.BRANCH_NAME, DATE(O.REQUESTED_AT);

CREATE OR REPLACE VIEW V_CONTRACT_PROFITABILITY AS
SELECT
    CT.CONTRACT_ID,
    CT.CONTRACT_NUMBER,
    CT.CLIENT_ID,
    COALESCE(SUM(I.TOTAL_AMOUNT) FILTER (WHERE I.STATUS <> 'RECHAZADA'), 0) AS REVENUE_AMOUNT,
    COALESCE(SUM(O.FUEL_COST + O.VIATICS_COST + O.MAINTENANCE_COST), 0) AS OPERATING_COST_AMOUNT,
    COALESCE(SUM(I.TOTAL_AMOUNT) FILTER (WHERE I.STATUS <> 'RECHAZADA'), 0)
        - COALESCE(SUM(O.FUEL_COST + O.VIATICS_COST + O.MAINTENANCE_COST), 0) AS GROSS_MARGIN_AMOUNT
FROM CONTRACTS CT
LEFT JOIN ORDERS O
    ON O.CONTRACT_ID = CT.CONTRACT_ID
LEFT JOIN INVOICES I
    ON I.ORDER_ID = O.ORDER_ID
GROUP BY CT.CONTRACT_ID, CT.CONTRACT_NUMBER, CT.CLIENT_ID;

INSERT INTO BRANCHES (BRANCH_CODE, BRANCH_NAME, CITY, COUNTRY)
VALUES
    ('GUA', 'SEDE GUATEMALA', 'CIUDAD DE GUATEMALA', 'GUATEMALA'),
    ('XELA', 'SEDE QUETZALTENANGO', 'QUETZALTENANGO', 'GUATEMALA'),
    ('PBAR', 'SEDE PUERTO BARRIOS', 'PUERTO BARRIOS', 'GUATEMALA');

INSERT INTO ROUTES (ROUTE_CODE, ORIGIN, DESTINATION, DISTANCE_KM, ESTIMATED_HOURS, IS_INTERNATIONAL)
VALUES
    ('PBAR-GUA', 'PUERTO BARRIOS', 'CIUDAD DE GUATEMALA', 300.00, 7.50, FALSE),
    ('GUA-PBAR', 'CIUDAD DE GUATEMALA', 'PUERTO BARRIOS', 300.00, 7.50, FALSE),
    ('GUA-XELA', 'CIUDAD DE GUATEMALA', 'QUETZALTENANGO', 200.00, 5.00, FALSE),
    ('XELA-GUA', 'QUETZALTENANGO', 'CIUDAD DE GUATEMALA', 200.00, 5.00, FALSE),
    ('PBAR-XELA', 'PUERTO BARRIOS', 'QUETZALTENANGO', 410.00, 10.00, FALSE),
    ('XELA-PBAR', 'QUETZALTENANGO', 'PUERTO BARRIOS', 410.00, 10.00, FALSE),
    ('GUA-SAL', 'CIUDAD DE GUATEMALA', 'SAN SALVADOR', 235.00, 5.50, TRUE),
    ('GUA-SPS', 'CIUDAD DE GUATEMALA', 'SAN PEDRO SULA', 410.00, 9.00, TRUE);

INSERT INTO VEHICLE_TYPES (TYPE_CODE, TYPE_NAME, MIN_CAPACITY_TON, MAX_CAPACITY_TON, RATE_PER_KM)
VALUES
    ('LIGHT', 'UNIDAD LIGERA', 0.00, 3.50, 8.00),
    ('HEAVY', 'CAMION PESADO', 10.00, 12.00, 12.50),
    ('TRAILER', 'CABEZAL_TRAILER', 22.00, NULL, 18.00);

INSERT INTO CARGO_TYPES (CARGO_NAME, REQUIRES_REFRIGERATION)
VALUES
    ('CARGA GENERAL', FALSE),
    ('CARGA REFRIGERADA', TRUE);

COMMIT;